package com.certapp.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbCertConfigExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    protected long start = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    protected long count = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public TbCertConfigExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public void setStart(long start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public long getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public void setCount(long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public long getCount() {
        return count;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCertNameIsNull() {
            addCriterion("cert_name is null");
            return (Criteria) this;
        }

        public Criteria andCertNameIsNotNull() {
            addCriterion("cert_name is not null");
            return (Criteria) this;
        }

        public Criteria andCertNameEqualTo(String value) {
            addCriterion("cert_name =", value, "certName");
            return (Criteria) this;
        }

        public Criteria andCertNameNotEqualTo(String value) {
            addCriterion("cert_name <>", value, "certName");
            return (Criteria) this;
        }

        public Criteria andCertNameGreaterThan(String value) {
            addCriterion("cert_name >", value, "certName");
            return (Criteria) this;
        }

        public Criteria andCertNameGreaterThanOrEqualTo(String value) {
            addCriterion("cert_name >=", value, "certName");
            return (Criteria) this;
        }

        public Criteria andCertNameLessThan(String value) {
            addCriterion("cert_name <", value, "certName");
            return (Criteria) this;
        }

        public Criteria andCertNameLessThanOrEqualTo(String value) {
            addCriterion("cert_name <=", value, "certName");
            return (Criteria) this;
        }

        public Criteria andCertNameLike(String value) {
            addCriterion("cert_name like", value, "certName");
            return (Criteria) this;
        }

        public Criteria andCertNameNotLike(String value) {
            addCriterion("cert_name not like", value, "certName");
            return (Criteria) this;
        }

        public Criteria andCertNameIn(List<String> values) {
            addCriterion("cert_name in", values, "certName");
            return (Criteria) this;
        }

        public Criteria andCertNameNotIn(List<String> values) {
            addCriterion("cert_name not in", values, "certName");
            return (Criteria) this;
        }

        public Criteria andCertNameBetween(String value1, String value2) {
            addCriterion("cert_name between", value1, value2, "certName");
            return (Criteria) this;
        }

        public Criteria andCertNameNotBetween(String value1, String value2) {
            addCriterion("cert_name not between", value1, value2, "certName");
            return (Criteria) this;
        }

        public Criteria andFiledFontIsNull() {
            addCriterion("filed_font is null");
            return (Criteria) this;
        }

        public Criteria andFiledFontIsNotNull() {
            addCriterion("filed_font is not null");
            return (Criteria) this;
        }

        public Criteria andFiledFontEqualTo(String value) {
            addCriterion("filed_font =", value, "filedFont");
            return (Criteria) this;
        }

        public Criteria andFiledFontNotEqualTo(String value) {
            addCriterion("filed_font <>", value, "filedFont");
            return (Criteria) this;
        }

        public Criteria andFiledFontGreaterThan(String value) {
            addCriterion("filed_font >", value, "filedFont");
            return (Criteria) this;
        }

        public Criteria andFiledFontGreaterThanOrEqualTo(String value) {
            addCriterion("filed_font >=", value, "filedFont");
            return (Criteria) this;
        }

        public Criteria andFiledFontLessThan(String value) {
            addCriterion("filed_font <", value, "filedFont");
            return (Criteria) this;
        }

        public Criteria andFiledFontLessThanOrEqualTo(String value) {
            addCriterion("filed_font <=", value, "filedFont");
            return (Criteria) this;
        }

        public Criteria andFiledFontLike(String value) {
            addCriterion("filed_font like", value, "filedFont");
            return (Criteria) this;
        }

        public Criteria andFiledFontNotLike(String value) {
            addCriterion("filed_font not like", value, "filedFont");
            return (Criteria) this;
        }

        public Criteria andFiledFontIn(List<String> values) {
            addCriterion("filed_font in", values, "filedFont");
            return (Criteria) this;
        }

        public Criteria andFiledFontNotIn(List<String> values) {
            addCriterion("filed_font not in", values, "filedFont");
            return (Criteria) this;
        }

        public Criteria andFiledFontBetween(String value1, String value2) {
            addCriterion("filed_font between", value1, value2, "filedFont");
            return (Criteria) this;
        }

        public Criteria andFiledFontNotBetween(String value1, String value2) {
            addCriterion("filed_font not between", value1, value2, "filedFont");
            return (Criteria) this;
        }

        public Criteria andQrCodeUrlIsNull() {
            addCriterion("qr_code_url is null");
            return (Criteria) this;
        }

        public Criteria andQrCodeUrlIsNotNull() {
            addCriterion("qr_code_url is not null");
            return (Criteria) this;
        }

        public Criteria andQrCodeUrlEqualTo(String value) {
            addCriterion("qr_code_url =", value, "qrCodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrCodeUrlNotEqualTo(String value) {
            addCriterion("qr_code_url <>", value, "qrCodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrCodeUrlGreaterThan(String value) {
            addCriterion("qr_code_url >", value, "qrCodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrCodeUrlGreaterThanOrEqualTo(String value) {
            addCriterion("qr_code_url >=", value, "qrCodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrCodeUrlLessThan(String value) {
            addCriterion("qr_code_url <", value, "qrCodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrCodeUrlLessThanOrEqualTo(String value) {
            addCriterion("qr_code_url <=", value, "qrCodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrCodeUrlLike(String value) {
            addCriterion("qr_code_url like", value, "qrCodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrCodeUrlNotLike(String value) {
            addCriterion("qr_code_url not like", value, "qrCodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrCodeUrlIn(List<String> values) {
            addCriterion("qr_code_url in", values, "qrCodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrCodeUrlNotIn(List<String> values) {
            addCriterion("qr_code_url not in", values, "qrCodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrCodeUrlBetween(String value1, String value2) {
            addCriterion("qr_code_url between", value1, value2, "qrCodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrCodeUrlNotBetween(String value1, String value2) {
            addCriterion("qr_code_url not between", value1, value2, "qrCodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrCodeLocalIsNull() {
            addCriterion("qr_code_local is null");
            return (Criteria) this;
        }

        public Criteria andQrCodeLocalIsNotNull() {
            addCriterion("qr_code_local is not null");
            return (Criteria) this;
        }

        public Criteria andQrCodeLocalEqualTo(String value) {
            addCriterion("qr_code_local =", value, "qrCodeLocal");
            return (Criteria) this;
        }

        public Criteria andQrCodeLocalNotEqualTo(String value) {
            addCriterion("qr_code_local <>", value, "qrCodeLocal");
            return (Criteria) this;
        }

        public Criteria andQrCodeLocalGreaterThan(String value) {
            addCriterion("qr_code_local >", value, "qrCodeLocal");
            return (Criteria) this;
        }

        public Criteria andQrCodeLocalGreaterThanOrEqualTo(String value) {
            addCriterion("qr_code_local >=", value, "qrCodeLocal");
            return (Criteria) this;
        }

        public Criteria andQrCodeLocalLessThan(String value) {
            addCriterion("qr_code_local <", value, "qrCodeLocal");
            return (Criteria) this;
        }

        public Criteria andQrCodeLocalLessThanOrEqualTo(String value) {
            addCriterion("qr_code_local <=", value, "qrCodeLocal");
            return (Criteria) this;
        }

        public Criteria andQrCodeLocalLike(String value) {
            addCriterion("qr_code_local like", value, "qrCodeLocal");
            return (Criteria) this;
        }

        public Criteria andQrCodeLocalNotLike(String value) {
            addCriterion("qr_code_local not like", value, "qrCodeLocal");
            return (Criteria) this;
        }

        public Criteria andQrCodeLocalIn(List<String> values) {
            addCriterion("qr_code_local in", values, "qrCodeLocal");
            return (Criteria) this;
        }

        public Criteria andQrCodeLocalNotIn(List<String> values) {
            addCriterion("qr_code_local not in", values, "qrCodeLocal");
            return (Criteria) this;
        }

        public Criteria andQrCodeLocalBetween(String value1, String value2) {
            addCriterion("qr_code_local between", value1, value2, "qrCodeLocal");
            return (Criteria) this;
        }

        public Criteria andQrCodeLocalNotBetween(String value1, String value2) {
            addCriterion("qr_code_local not between", value1, value2, "qrCodeLocal");
            return (Criteria) this;
        }

        public Criteria andNumberLocalIsNull() {
            addCriterion("number_local is null");
            return (Criteria) this;
        }

        public Criteria andNumberLocalIsNotNull() {
            addCriterion("number_local is not null");
            return (Criteria) this;
        }

        public Criteria andNumberLocalEqualTo(String value) {
            addCriterion("number_local =", value, "numberLocal");
            return (Criteria) this;
        }

        public Criteria andNumberLocalNotEqualTo(String value) {
            addCriterion("number_local <>", value, "numberLocal");
            return (Criteria) this;
        }

        public Criteria andNumberLocalGreaterThan(String value) {
            addCriterion("number_local >", value, "numberLocal");
            return (Criteria) this;
        }

        public Criteria andNumberLocalGreaterThanOrEqualTo(String value) {
            addCriterion("number_local >=", value, "numberLocal");
            return (Criteria) this;
        }

        public Criteria andNumberLocalLessThan(String value) {
            addCriterion("number_local <", value, "numberLocal");
            return (Criteria) this;
        }

        public Criteria andNumberLocalLessThanOrEqualTo(String value) {
            addCriterion("number_local <=", value, "numberLocal");
            return (Criteria) this;
        }

        public Criteria andNumberLocalLike(String value) {
            addCriterion("number_local like", value, "numberLocal");
            return (Criteria) this;
        }

        public Criteria andNumberLocalNotLike(String value) {
            addCriterion("number_local not like", value, "numberLocal");
            return (Criteria) this;
        }

        public Criteria andNumberLocalIn(List<String> values) {
            addCriterion("number_local in", values, "numberLocal");
            return (Criteria) this;
        }

        public Criteria andNumberLocalNotIn(List<String> values) {
            addCriterion("number_local not in", values, "numberLocal");
            return (Criteria) this;
        }

        public Criteria andNumberLocalBetween(String value1, String value2) {
            addCriterion("number_local between", value1, value2, "numberLocal");
            return (Criteria) this;
        }

        public Criteria andNumberLocalNotBetween(String value1, String value2) {
            addCriterion("number_local not between", value1, value2, "numberLocal");
            return (Criteria) this;
        }

        public Criteria andNumFontIsNull() {
            addCriterion("num_font is null");
            return (Criteria) this;
        }

        public Criteria andNumFontIsNotNull() {
            addCriterion("num_font is not null");
            return (Criteria) this;
        }

        public Criteria andNumFontEqualTo(String value) {
            addCriterion("num_font =", value, "numFont");
            return (Criteria) this;
        }

        public Criteria andNumFontNotEqualTo(String value) {
            addCriterion("num_font <>", value, "numFont");
            return (Criteria) this;
        }

        public Criteria andNumFontGreaterThan(String value) {
            addCriterion("num_font >", value, "numFont");
            return (Criteria) this;
        }

        public Criteria andNumFontGreaterThanOrEqualTo(String value) {
            addCriterion("num_font >=", value, "numFont");
            return (Criteria) this;
        }

        public Criteria andNumFontLessThan(String value) {
            addCriterion("num_font <", value, "numFont");
            return (Criteria) this;
        }

        public Criteria andNumFontLessThanOrEqualTo(String value) {
            addCriterion("num_font <=", value, "numFont");
            return (Criteria) this;
        }

        public Criteria andNumFontLike(String value) {
            addCriterion("num_font like", value, "numFont");
            return (Criteria) this;
        }

        public Criteria andNumFontNotLike(String value) {
            addCriterion("num_font not like", value, "numFont");
            return (Criteria) this;
        }

        public Criteria andNumFontIn(List<String> values) {
            addCriterion("num_font in", values, "numFont");
            return (Criteria) this;
        }

        public Criteria andNumFontNotIn(List<String> values) {
            addCriterion("num_font not in", values, "numFont");
            return (Criteria) this;
        }

        public Criteria andNumFontBetween(String value1, String value2) {
            addCriterion("num_font between", value1, value2, "numFont");
            return (Criteria) this;
        }

        public Criteria andNumFontNotBetween(String value1, String value2) {
            addCriterion("num_font not between", value1, value2, "numFont");
            return (Criteria) this;
        }

        public Criteria andCertDescIsNull() {
            addCriterion("cert_desc is null");
            return (Criteria) this;
        }

        public Criteria andCertDescIsNotNull() {
            addCriterion("cert_desc is not null");
            return (Criteria) this;
        }

        public Criteria andCertDescEqualTo(String value) {
            addCriterion("cert_desc =", value, "certDesc");
            return (Criteria) this;
        }

        public Criteria andCertDescNotEqualTo(String value) {
            addCriterion("cert_desc <>", value, "certDesc");
            return (Criteria) this;
        }

        public Criteria andCertDescGreaterThan(String value) {
            addCriterion("cert_desc >", value, "certDesc");
            return (Criteria) this;
        }

        public Criteria andCertDescGreaterThanOrEqualTo(String value) {
            addCriterion("cert_desc >=", value, "certDesc");
            return (Criteria) this;
        }

        public Criteria andCertDescLessThan(String value) {
            addCriterion("cert_desc <", value, "certDesc");
            return (Criteria) this;
        }

        public Criteria andCertDescLessThanOrEqualTo(String value) {
            addCriterion("cert_desc <=", value, "certDesc");
            return (Criteria) this;
        }

        public Criteria andCertDescLike(String value) {
            addCriterion("cert_desc like", value, "certDesc");
            return (Criteria) this;
        }

        public Criteria andCertDescNotLike(String value) {
            addCriterion("cert_desc not like", value, "certDesc");
            return (Criteria) this;
        }

        public Criteria andCertDescIn(List<String> values) {
            addCriterion("cert_desc in", values, "certDesc");
            return (Criteria) this;
        }

        public Criteria andCertDescNotIn(List<String> values) {
            addCriterion("cert_desc not in", values, "certDesc");
            return (Criteria) this;
        }

        public Criteria andCertDescBetween(String value1, String value2) {
            addCriterion("cert_desc between", value1, value2, "certDesc");
            return (Criteria) this;
        }

        public Criteria andCertDescNotBetween(String value1, String value2) {
            addCriterion("cert_desc not between", value1, value2, "certDesc");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andCertRealIsNull() {
            addCriterion("cert_real is null");
            return (Criteria) this;
        }

        public Criteria andCertRealIsNotNull() {
            addCriterion("cert_real is not null");
            return (Criteria) this;
        }

        public Criteria andCertRealEqualTo(Integer value) {
            addCriterion("cert_real =", value, "certReal");
            return (Criteria) this;
        }

        public Criteria andCertRealNotEqualTo(Integer value) {
            addCriterion("cert_real <>", value, "certReal");
            return (Criteria) this;
        }

        public Criteria andCertRealGreaterThan(Integer value) {
            addCriterion("cert_real >", value, "certReal");
            return (Criteria) this;
        }

        public Criteria andCertRealGreaterThanOrEqualTo(Integer value) {
            addCriterion("cert_real >=", value, "certReal");
            return (Criteria) this;
        }

        public Criteria andCertRealLessThan(Integer value) {
            addCriterion("cert_real <", value, "certReal");
            return (Criteria) this;
        }

        public Criteria andCertRealLessThanOrEqualTo(Integer value) {
            addCriterion("cert_real <=", value, "certReal");
            return (Criteria) this;
        }

        public Criteria andCertRealIn(List<Integer> values) {
            addCriterion("cert_real in", values, "certReal");
            return (Criteria) this;
        }

        public Criteria andCertRealNotIn(List<Integer> values) {
            addCriterion("cert_real not in", values, "certReal");
            return (Criteria) this;
        }

        public Criteria andCertRealBetween(Integer value1, Integer value2) {
            addCriterion("cert_real between", value1, value2, "certReal");
            return (Criteria) this;
        }

        public Criteria andCertRealNotBetween(Integer value1, Integer value2) {
            addCriterion("cert_real not between", value1, value2, "certReal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_cert_config
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
