package com.certapp.dao.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@EqualsAndHashCode
public class TbCertConfig implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_config.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_config.cert_name
     *
     * @mbg.generated
     */
    private String certName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_config.filed_font
     *
     * @mbg.generated
     */
    private String filedFont;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_config.qr_code_url
     *
     * @mbg.generated
     */
    private String qrCodeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_config.qr_code_local
     *
     * @mbg.generated
     */
    private String qrCodeLocal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_config.number_local
     *
     * @mbg.generated
     */
    private String numberLocal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_config.num_font
     *
     * @mbg.generated
     */
    private String numFont;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_config.cert_desc
     *
     * @mbg.generated
     */
    private String certDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_config.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_config.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_config.cert_real
     *
     * @mbg.generated
     */
    private Integer certReal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_config.base_map
     *
     * @mbg.generated
     */
    private String baseMap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_config.pic_preview
     *
     * @mbg.generated
     */
    private String picPreview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}
