package com.certapp.dao.entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class TbCertInfoExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    protected long start = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    protected long count = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public TbCertInfoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public void setStart(long start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public long getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public void setCount(long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public long getCount() {
        return count;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdIsNull() {
            addCriterion("cert_config_id is null");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdIsNotNull() {
            addCriterion("cert_config_id is not null");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdEqualTo(Integer value) {
            addCriterion("cert_config_id =", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdNotEqualTo(Integer value) {
            addCriterion("cert_config_id <>", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdGreaterThan(Integer value) {
            addCriterion("cert_config_id >", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cert_config_id >=", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdLessThan(Integer value) {
            addCriterion("cert_config_id <", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdLessThanOrEqualTo(Integer value) {
            addCriterion("cert_config_id <=", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdIn(List<Integer> values) {
            addCriterion("cert_config_id in", values, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdNotIn(List<Integer> values) {
            addCriterion("cert_config_id not in", values, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdBetween(Integer value1, Integer value2) {
            addCriterion("cert_config_id between", value1, value2, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cert_config_id not between", value1, value2, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertIdIsNull() {
            addCriterion("cert_id is null");
            return (Criteria) this;
        }

        public Criteria andCertIdIsNotNull() {
            addCriterion("cert_id is not null");
            return (Criteria) this;
        }

        public Criteria andCertIdEqualTo(String value) {
            addCriterion("cert_id =", value, "certId");
            return (Criteria) this;
        }

        public Criteria andCertIdNotEqualTo(String value) {
            addCriterion("cert_id <>", value, "certId");
            return (Criteria) this;
        }

        public Criteria andCertIdGreaterThan(String value) {
            addCriterion("cert_id >", value, "certId");
            return (Criteria) this;
        }

        public Criteria andCertIdGreaterThanOrEqualTo(String value) {
            addCriterion("cert_id >=", value, "certId");
            return (Criteria) this;
        }

        public Criteria andCertIdLessThan(String value) {
            addCriterion("cert_id <", value, "certId");
            return (Criteria) this;
        }

        public Criteria andCertIdLessThanOrEqualTo(String value) {
            addCriterion("cert_id <=", value, "certId");
            return (Criteria) this;
        }

        public Criteria andCertIdLike(String value) {
            addCriterion("cert_id like", value, "certId");
            return (Criteria) this;
        }

        public Criteria andCertIdNotLike(String value) {
            addCriterion("cert_id not like", value, "certId");
            return (Criteria) this;
        }

        public Criteria andCertIdIn(List<String> values) {
            addCriterion("cert_id in", values, "certId");
            return (Criteria) this;
        }

        public Criteria andCertIdNotIn(List<String> values) {
            addCriterion("cert_id not in", values, "certId");
            return (Criteria) this;
        }

        public Criteria andCertIdBetween(String value1, String value2) {
            addCriterion("cert_id between", value1, value2, "certId");
            return (Criteria) this;
        }

        public Criteria andCertIdNotBetween(String value1, String value2) {
            addCriterion("cert_id not between", value1, value2, "certId");
            return (Criteria) this;
        }

        public Criteria andFiledInfoIsNull() {
            addCriterion("filed_info is null");
            return (Criteria) this;
        }

        public Criteria andFiledInfoIsNotNull() {
            addCriterion("filed_info is not null");
            return (Criteria) this;
        }

        public Criteria andFiledInfoEqualTo(String value) {
            addCriterion("filed_info =", value, "filedInfo");
            return (Criteria) this;
        }

        public Criteria andFiledInfoNotEqualTo(String value) {
            addCriterion("filed_info <>", value, "filedInfo");
            return (Criteria) this;
        }

        public Criteria andFiledInfoGreaterThan(String value) {
            addCriterion("filed_info >", value, "filedInfo");
            return (Criteria) this;
        }

        public Criteria andFiledInfoGreaterThanOrEqualTo(String value) {
            addCriterion("filed_info >=", value, "filedInfo");
            return (Criteria) this;
        }

        public Criteria andFiledInfoLessThan(String value) {
            addCriterion("filed_info <", value, "filedInfo");
            return (Criteria) this;
        }

        public Criteria andFiledInfoLessThanOrEqualTo(String value) {
            addCriterion("filed_info <=", value, "filedInfo");
            return (Criteria) this;
        }

        public Criteria andFiledInfoLike(String value) {
            addCriterion("filed_info like", value, "filedInfo");
            return (Criteria) this;
        }

        public Criteria andFiledInfoNotLike(String value) {
            addCriterion("filed_info not like", value, "filedInfo");
            return (Criteria) this;
        }

        public Criteria andFiledInfoIn(List<String> values) {
            addCriterion("filed_info in", values, "filedInfo");
            return (Criteria) this;
        }

        public Criteria andFiledInfoNotIn(List<String> values) {
            addCriterion("filed_info not in", values, "filedInfo");
            return (Criteria) this;
        }

        public Criteria andFiledInfoBetween(String value1, String value2) {
            addCriterion("filed_info between", value1, value2, "filedInfo");
            return (Criteria) this;
        }

        public Criteria andFiledInfoNotBetween(String value1, String value2) {
            addCriterion("filed_info not between", value1, value2, "filedInfo");
            return (Criteria) this;
        }

        public Criteria andCertHashIsNull() {
            addCriterion("cert_hash is null");
            return (Criteria) this;
        }

        public Criteria andCertHashIsNotNull() {
            addCriterion("cert_hash is not null");
            return (Criteria) this;
        }

        public Criteria andCertHashEqualTo(String value) {
            addCriterion("cert_hash =", value, "certHash");
            return (Criteria) this;
        }

        public Criteria andCertHashNotEqualTo(String value) {
            addCriterion("cert_hash <>", value, "certHash");
            return (Criteria) this;
        }

        public Criteria andCertHashGreaterThan(String value) {
            addCriterion("cert_hash >", value, "certHash");
            return (Criteria) this;
        }

        public Criteria andCertHashGreaterThanOrEqualTo(String value) {
            addCriterion("cert_hash >=", value, "certHash");
            return (Criteria) this;
        }

        public Criteria andCertHashLessThan(String value) {
            addCriterion("cert_hash <", value, "certHash");
            return (Criteria) this;
        }

        public Criteria andCertHashLessThanOrEqualTo(String value) {
            addCriterion("cert_hash <=", value, "certHash");
            return (Criteria) this;
        }

        public Criteria andCertHashLike(String value) {
            addCriterion("cert_hash like", value, "certHash");
            return (Criteria) this;
        }

        public Criteria andCertHashNotLike(String value) {
            addCriterion("cert_hash not like", value, "certHash");
            return (Criteria) this;
        }

        public Criteria andCertHashIn(List<String> values) {
            addCriterion("cert_hash in", values, "certHash");
            return (Criteria) this;
        }

        public Criteria andCertHashNotIn(List<String> values) {
            addCriterion("cert_hash not in", values, "certHash");
            return (Criteria) this;
        }

        public Criteria andCertHashBetween(String value1, String value2) {
            addCriterion("cert_hash between", value1, value2, "certHash");
            return (Criteria) this;
        }

        public Criteria andCertHashNotBetween(String value1, String value2) {
            addCriterion("cert_hash not between", value1, value2, "certHash");
            return (Criteria) this;
        }

        public Criteria andTxHashIsNull() {
            addCriterion("tx_hash is null");
            return (Criteria) this;
        }

        public Criteria andTxHashIsNotNull() {
            addCriterion("tx_hash is not null");
            return (Criteria) this;
        }

        public Criteria andTxHashEqualTo(String value) {
            addCriterion("tx_hash =", value, "txHash");
            return (Criteria) this;
        }

        public Criteria andTxHashNotEqualTo(String value) {
            addCriterion("tx_hash <>", value, "txHash");
            return (Criteria) this;
        }

        public Criteria andTxHashGreaterThan(String value) {
            addCriterion("tx_hash >", value, "txHash");
            return (Criteria) this;
        }

        public Criteria andTxHashGreaterThanOrEqualTo(String value) {
            addCriterion("tx_hash >=", value, "txHash");
            return (Criteria) this;
        }

        public Criteria andTxHashLessThan(String value) {
            addCriterion("tx_hash <", value, "txHash");
            return (Criteria) this;
        }

        public Criteria andTxHashLessThanOrEqualTo(String value) {
            addCriterion("tx_hash <=", value, "txHash");
            return (Criteria) this;
        }

        public Criteria andTxHashLike(String value) {
            addCriterion("tx_hash like", value, "txHash");
            return (Criteria) this;
        }

        public Criteria andTxHashNotLike(String value) {
            addCriterion("tx_hash not like", value, "txHash");
            return (Criteria) this;
        }

        public Criteria andTxHashIn(List<String> values) {
            addCriterion("tx_hash in", values, "txHash");
            return (Criteria) this;
        }

        public Criteria andTxHashNotIn(List<String> values) {
            addCriterion("tx_hash not in", values, "txHash");
            return (Criteria) this;
        }

        public Criteria andTxHashBetween(String value1, String value2) {
            addCriterion("tx_hash between", value1, value2, "txHash");
            return (Criteria) this;
        }

        public Criteria andTxHashNotBetween(String value1, String value2) {
            addCriterion("tx_hash not between", value1, value2, "txHash");
            return (Criteria) this;
        }

        public Criteria andCertUrlIsNull() {
            addCriterion("cert_url is null");
            return (Criteria) this;
        }

        public Criteria andCertUrlIsNotNull() {
            addCriterion("cert_url is not null");
            return (Criteria) this;
        }

        public Criteria andCertUrlEqualTo(String value) {
            addCriterion("cert_url =", value, "certUrl");
            return (Criteria) this;
        }

        public Criteria andCertUrlNotEqualTo(String value) {
            addCriterion("cert_url <>", value, "certUrl");
            return (Criteria) this;
        }

        public Criteria andCertUrlGreaterThan(String value) {
            addCriterion("cert_url >", value, "certUrl");
            return (Criteria) this;
        }

        public Criteria andCertUrlGreaterThanOrEqualTo(String value) {
            addCriterion("cert_url >=", value, "certUrl");
            return (Criteria) this;
        }

        public Criteria andCertUrlLessThan(String value) {
            addCriterion("cert_url <", value, "certUrl");
            return (Criteria) this;
        }

        public Criteria andCertUrlLessThanOrEqualTo(String value) {
            addCriterion("cert_url <=", value, "certUrl");
            return (Criteria) this;
        }

        public Criteria andCertUrlLike(String value) {
            addCriterion("cert_url like", value, "certUrl");
            return (Criteria) this;
        }

        public Criteria andCertUrlNotLike(String value) {
            addCriterion("cert_url not like", value, "certUrl");
            return (Criteria) this;
        }

        public Criteria andCertUrlIn(List<String> values) {
            addCriterion("cert_url in", values, "certUrl");
            return (Criteria) this;
        }

        public Criteria andCertUrlNotIn(List<String> values) {
            addCriterion("cert_url not in", values, "certUrl");
            return (Criteria) this;
        }

        public Criteria andCertUrlBetween(String value1, String value2) {
            addCriterion("cert_url between", value1, value2, "certUrl");
            return (Criteria) this;
        }

        public Criteria andCertUrlNotBetween(String value1, String value2) {
            addCriterion("cert_url not between", value1, value2, "certUrl");
            return (Criteria) this;
        }

        public Criteria andCertStateIsNull() {
            addCriterion("cert_state is null");
            return (Criteria) this;
        }

        public Criteria andCertStateIsNotNull() {
            addCriterion("cert_state is not null");
            return (Criteria) this;
        }

        public Criteria andCertStateEqualTo(Integer value) {
            addCriterion("cert_state =", value, "certState");
            return (Criteria) this;
        }

        public Criteria andCertStateNotEqualTo(Integer value) {
            addCriterion("cert_state <>", value, "certState");
            return (Criteria) this;
        }

        public Criteria andCertStateGreaterThan(Integer value) {
            addCriterion("cert_state >", value, "certState");
            return (Criteria) this;
        }

        public Criteria andCertStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("cert_state >=", value, "certState");
            return (Criteria) this;
        }

        public Criteria andCertStateLessThan(Integer value) {
            addCriterion("cert_state <", value, "certState");
            return (Criteria) this;
        }

        public Criteria andCertStateLessThanOrEqualTo(Integer value) {
            addCriterion("cert_state <=", value, "certState");
            return (Criteria) this;
        }

        public Criteria andCertStateIn(List<Integer> values) {
            addCriterion("cert_state in", values, "certState");
            return (Criteria) this;
        }

        public Criteria andCertStateNotIn(List<Integer> values) {
            addCriterion("cert_state not in", values, "certState");
            return (Criteria) this;
        }

        public Criteria andCertStateBetween(Integer value1, Integer value2) {
            addCriterion("cert_state between", value1, value2, "certState");
            return (Criteria) this;
        }

        public Criteria andCertStateNotBetween(Integer value1, Integer value2) {
            addCriterion("cert_state not between", value1, value2, "certState");
            return (Criteria) this;
        }

        public Criteria andPublishStateIsNull() {
            addCriterion("publish_state is null");
            return (Criteria) this;
        }

        public Criteria andPublishStateIsNotNull() {
            addCriterion("publish_state is not null");
            return (Criteria) this;
        }

        public Criteria andPublishStateEqualTo(Integer value) {
            addCriterion("publish_state =", value, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateNotEqualTo(Integer value) {
            addCriterion("publish_state <>", value, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateGreaterThan(Integer value) {
            addCriterion("publish_state >", value, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("publish_state >=", value, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateLessThan(Integer value) {
            addCriterion("publish_state <", value, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateLessThanOrEqualTo(Integer value) {
            addCriterion("publish_state <=", value, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateIn(List<Integer> values) {
            addCriterion("publish_state in", values, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateNotIn(List<Integer> values) {
            addCriterion("publish_state not in", values, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateBetween(Integer value1, Integer value2) {
            addCriterion("publish_state between", value1, value2, "publishState");
            return (Criteria) this;
        }

        public Criteria andPublishStateNotBetween(Integer value1, Integer value2) {
            addCriterion("publish_state not between", value1, value2, "publishState");
            return (Criteria) this;
        }

        public Criteria andCertTimeIsNull() {
            addCriterion("cert_time is null");
            return (Criteria) this;
        }

        public Criteria andCertTimeIsNotNull() {
            addCriterion("cert_time is not null");
            return (Criteria) this;
        }

        public Criteria andCertTimeEqualTo(Date value) {
            addCriterion("cert_time =", value, "certTime");
            return (Criteria) this;
        }

        public Criteria andCertTimeNotEqualTo(Date value) {
            addCriterion("cert_time <>", value, "certTime");
            return (Criteria) this;
        }

        public Criteria andCertTimeGreaterThan(Date value) {
            addCriterion("cert_time >", value, "certTime");
            return (Criteria) this;
        }

        public Criteria andCertTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cert_time >=", value, "certTime");
            return (Criteria) this;
        }

        public Criteria andCertTimeLessThan(Date value) {
            addCriterion("cert_time <", value, "certTime");
            return (Criteria) this;
        }

        public Criteria andCertTimeLessThanOrEqualTo(Date value) {
            addCriterion("cert_time <=", value, "certTime");
            return (Criteria) this;
        }

        public Criteria andCertTimeIn(List<Date> values) {
            addCriterion("cert_time in", values, "certTime");
            return (Criteria) this;
        }

        public Criteria andCertTimeNotIn(List<Date> values) {
            addCriterion("cert_time not in", values, "certTime");
            return (Criteria) this;
        }

        public Criteria andCertTimeBetween(Date value1, Date value2) {
            addCriterion("cert_time between", value1, value2, "certTime");
            return (Criteria) this;
        }

        public Criteria andCertTimeNotBetween(Date value1, Date value2) {
            addCriterion("cert_time not between", value1, value2, "certTime");
            return (Criteria) this;
        }

        public Criteria andSearchFiledIsNull() {
            addCriterion("search_filed is null");
            return (Criteria) this;
        }

        public Criteria andSearchFiledIsNotNull() {
            addCriterion("search_filed is not null");
            return (Criteria) this;
        }

        public Criteria andSearchFiledEqualTo(String value) {
            addCriterion("search_filed =", value, "searchFiled");
            return (Criteria) this;
        }

        public Criteria andSearchFiledNotEqualTo(String value) {
            addCriterion("search_filed <>", value, "searchFiled");
            return (Criteria) this;
        }

        public Criteria andSearchFiledGreaterThan(String value) {
            addCriterion("search_filed >", value, "searchFiled");
            return (Criteria) this;
        }

        public Criteria andSearchFiledGreaterThanOrEqualTo(String value) {
            addCriterion("search_filed >=", value, "searchFiled");
            return (Criteria) this;
        }

        public Criteria andSearchFiledLessThan(String value) {
            addCriterion("search_filed <", value, "searchFiled");
            return (Criteria) this;
        }

        public Criteria andSearchFiledLessThanOrEqualTo(String value) {
            addCriterion("search_filed <=", value, "searchFiled");
            return (Criteria) this;
        }

        public Criteria andSearchFiledLike(String value) {
            addCriterion("search_filed like", value, "searchFiled");
            return (Criteria) this;
        }

        public Criteria andSearchFiledNotLike(String value) {
            addCriterion("search_filed not like", value, "searchFiled");
            return (Criteria) this;
        }

        public Criteria andSearchFiledIn(List<String> values) {
            addCriterion("search_filed in", values, "searchFiled");
            return (Criteria) this;
        }

        public Criteria andSearchFiledNotIn(List<String> values) {
            addCriterion("search_filed not in", values, "searchFiled");
            return (Criteria) this;
        }

        public Criteria andSearchFiledBetween(String value1, String value2) {
            addCriterion("search_filed between", value1, value2, "searchFiled");
            return (Criteria) this;
        }

        public Criteria andSearchFiledNotBetween(String value1, String value2) {
            addCriterion("search_filed not between", value1, value2, "searchFiled");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_cert_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
