package com.certapp.dao.entity;

import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import java.util.Date;

@Data
@ToString
@NoArgsConstructor
@EqualsAndHashCode
public class TbCertInfo implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_info.cert_config_id
     *
     * @mbg.generated
     */
    private Integer certConfigId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_info.cert_id
     *
     * @mbg.generated
     */
    private String certId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_info.filed_info
     *
     * @mbg.generated
     */
    private String filedInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_info.cert_hash
     *
     * @mbg.generated
     */
    private String certHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_info.tx_hash
     *
     * @mbg.generated
     */
    private String txHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_info.cert_url
     *
     * @mbg.generated
     */
    private String certUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_info.cert_state
     *
     * @mbg.generated
     */
    private Integer certState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_info.publish_state
     *
     * @mbg.generated
     */
    private Integer publishState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_info.cert_time
     *
     * @mbg.generated
     */
    private Date certTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_info.search_filed
     *
     * @mbg.generated
     */
    private String searchFiled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cert_info.cert_pic
     *
     * @mbg.generated
     */
    private String certPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}
