package com.certapp.dao.entity;

import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@EqualsAndHashCode
public class TbFiledInfo implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_filed_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_filed_info.cert_config_id
     *
     * @mbg.generated
     */
    private Integer certConfigId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_filed_info.filed_serial
     *
     * @mbg.generated
     */
    private String filedSerial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_filed_info.filed_name
     *
     * @mbg.generated
     */
    private String filedName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_filed_info.filed_name_zh
     *
     * @mbg.generated
     */
    private String filedNameZh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_filed_info.filed_local
     *
     * @mbg.generated
     */
    private String filedLocal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_filed_info.show_enable
     *
     * @mbg.generated
     */
    private Integer showEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_filed_info.filed_demo
     *
     * @mbg.generated
     */
    private String filedDemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}
