package com.certapp.dao.entity;

import java.util.ArrayList;
import java.util.List;

public class TbFiledInfoExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    protected long start = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    protected long count = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    public TbFiledInfoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    public void setStart(long start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    public long getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    public void setCount(long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    public long getCount() {
        return count;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdIsNull() {
            addCriterion("cert_config_id is null");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdIsNotNull() {
            addCriterion("cert_config_id is not null");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdEqualTo(Integer value) {
            addCriterion("cert_config_id =", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdNotEqualTo(Integer value) {
            addCriterion("cert_config_id <>", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdGreaterThan(Integer value) {
            addCriterion("cert_config_id >", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cert_config_id >=", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdLessThan(Integer value) {
            addCriterion("cert_config_id <", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdLessThanOrEqualTo(Integer value) {
            addCriterion("cert_config_id <=", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdIn(List<Integer> values) {
            addCriterion("cert_config_id in", values, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdNotIn(List<Integer> values) {
            addCriterion("cert_config_id not in", values, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdBetween(Integer value1, Integer value2) {
            addCriterion("cert_config_id between", value1, value2, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cert_config_id not between", value1, value2, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andFiledSerialIsNull() {
            addCriterion("filed_serial is null");
            return (Criteria) this;
        }

        public Criteria andFiledSerialIsNotNull() {
            addCriterion("filed_serial is not null");
            return (Criteria) this;
        }

        public Criteria andFiledSerialEqualTo(String value) {
            addCriterion("filed_serial =", value, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialNotEqualTo(String value) {
            addCriterion("filed_serial <>", value, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialGreaterThan(String value) {
            addCriterion("filed_serial >", value, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialGreaterThanOrEqualTo(String value) {
            addCriterion("filed_serial >=", value, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialLessThan(String value) {
            addCriterion("filed_serial <", value, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialLessThanOrEqualTo(String value) {
            addCriterion("filed_serial <=", value, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialLike(String value) {
            addCriterion("filed_serial like", value, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialNotLike(String value) {
            addCriterion("filed_serial not like", value, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialIn(List<String> values) {
            addCriterion("filed_serial in", values, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialNotIn(List<String> values) {
            addCriterion("filed_serial not in", values, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialBetween(String value1, String value2) {
            addCriterion("filed_serial between", value1, value2, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialNotBetween(String value1, String value2) {
            addCriterion("filed_serial not between", value1, value2, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledNameIsNull() {
            addCriterion("filed_name is null");
            return (Criteria) this;
        }

        public Criteria andFiledNameIsNotNull() {
            addCriterion("filed_name is not null");
            return (Criteria) this;
        }

        public Criteria andFiledNameEqualTo(String value) {
            addCriterion("filed_name =", value, "filedName");
            return (Criteria) this;
        }

        public Criteria andFiledNameNotEqualTo(String value) {
            addCriterion("filed_name <>", value, "filedName");
            return (Criteria) this;
        }

        public Criteria andFiledNameGreaterThan(String value) {
            addCriterion("filed_name >", value, "filedName");
            return (Criteria) this;
        }

        public Criteria andFiledNameGreaterThanOrEqualTo(String value) {
            addCriterion("filed_name >=", value, "filedName");
            return (Criteria) this;
        }

        public Criteria andFiledNameLessThan(String value) {
            addCriterion("filed_name <", value, "filedName");
            return (Criteria) this;
        }

        public Criteria andFiledNameLessThanOrEqualTo(String value) {
            addCriterion("filed_name <=", value, "filedName");
            return (Criteria) this;
        }

        public Criteria andFiledNameLike(String value) {
            addCriterion("filed_name like", value, "filedName");
            return (Criteria) this;
        }

        public Criteria andFiledNameNotLike(String value) {
            addCriterion("filed_name not like", value, "filedName");
            return (Criteria) this;
        }

        public Criteria andFiledNameIn(List<String> values) {
            addCriterion("filed_name in", values, "filedName");
            return (Criteria) this;
        }

        public Criteria andFiledNameNotIn(List<String> values) {
            addCriterion("filed_name not in", values, "filedName");
            return (Criteria) this;
        }

        public Criteria andFiledNameBetween(String value1, String value2) {
            addCriterion("filed_name between", value1, value2, "filedName");
            return (Criteria) this;
        }

        public Criteria andFiledNameNotBetween(String value1, String value2) {
            addCriterion("filed_name not between", value1, value2, "filedName");
            return (Criteria) this;
        }

        public Criteria andFiledNameZhIsNull() {
            addCriterion("filed_name_zh is null");
            return (Criteria) this;
        }

        public Criteria andFiledNameZhIsNotNull() {
            addCriterion("filed_name_zh is not null");
            return (Criteria) this;
        }

        public Criteria andFiledNameZhEqualTo(String value) {
            addCriterion("filed_name_zh =", value, "filedNameZh");
            return (Criteria) this;
        }

        public Criteria andFiledNameZhNotEqualTo(String value) {
            addCriterion("filed_name_zh <>", value, "filedNameZh");
            return (Criteria) this;
        }

        public Criteria andFiledNameZhGreaterThan(String value) {
            addCriterion("filed_name_zh >", value, "filedNameZh");
            return (Criteria) this;
        }

        public Criteria andFiledNameZhGreaterThanOrEqualTo(String value) {
            addCriterion("filed_name_zh >=", value, "filedNameZh");
            return (Criteria) this;
        }

        public Criteria andFiledNameZhLessThan(String value) {
            addCriterion("filed_name_zh <", value, "filedNameZh");
            return (Criteria) this;
        }

        public Criteria andFiledNameZhLessThanOrEqualTo(String value) {
            addCriterion("filed_name_zh <=", value, "filedNameZh");
            return (Criteria) this;
        }

        public Criteria andFiledNameZhLike(String value) {
            addCriterion("filed_name_zh like", value, "filedNameZh");
            return (Criteria) this;
        }

        public Criteria andFiledNameZhNotLike(String value) {
            addCriterion("filed_name_zh not like", value, "filedNameZh");
            return (Criteria) this;
        }

        public Criteria andFiledNameZhIn(List<String> values) {
            addCriterion("filed_name_zh in", values, "filedNameZh");
            return (Criteria) this;
        }

        public Criteria andFiledNameZhNotIn(List<String> values) {
            addCriterion("filed_name_zh not in", values, "filedNameZh");
            return (Criteria) this;
        }

        public Criteria andFiledNameZhBetween(String value1, String value2) {
            addCriterion("filed_name_zh between", value1, value2, "filedNameZh");
            return (Criteria) this;
        }

        public Criteria andFiledNameZhNotBetween(String value1, String value2) {
            addCriterion("filed_name_zh not between", value1, value2, "filedNameZh");
            return (Criteria) this;
        }

        public Criteria andFiledLocalIsNull() {
            addCriterion("filed_local is null");
            return (Criteria) this;
        }

        public Criteria andFiledLocalIsNotNull() {
            addCriterion("filed_local is not null");
            return (Criteria) this;
        }

        public Criteria andFiledLocalEqualTo(String value) {
            addCriterion("filed_local =", value, "filedLocal");
            return (Criteria) this;
        }

        public Criteria andFiledLocalNotEqualTo(String value) {
            addCriterion("filed_local <>", value, "filedLocal");
            return (Criteria) this;
        }

        public Criteria andFiledLocalGreaterThan(String value) {
            addCriterion("filed_local >", value, "filedLocal");
            return (Criteria) this;
        }

        public Criteria andFiledLocalGreaterThanOrEqualTo(String value) {
            addCriterion("filed_local >=", value, "filedLocal");
            return (Criteria) this;
        }

        public Criteria andFiledLocalLessThan(String value) {
            addCriterion("filed_local <", value, "filedLocal");
            return (Criteria) this;
        }

        public Criteria andFiledLocalLessThanOrEqualTo(String value) {
            addCriterion("filed_local <=", value, "filedLocal");
            return (Criteria) this;
        }

        public Criteria andFiledLocalLike(String value) {
            addCriterion("filed_local like", value, "filedLocal");
            return (Criteria) this;
        }

        public Criteria andFiledLocalNotLike(String value) {
            addCriterion("filed_local not like", value, "filedLocal");
            return (Criteria) this;
        }

        public Criteria andFiledLocalIn(List<String> values) {
            addCriterion("filed_local in", values, "filedLocal");
            return (Criteria) this;
        }

        public Criteria andFiledLocalNotIn(List<String> values) {
            addCriterion("filed_local not in", values, "filedLocal");
            return (Criteria) this;
        }

        public Criteria andFiledLocalBetween(String value1, String value2) {
            addCriterion("filed_local between", value1, value2, "filedLocal");
            return (Criteria) this;
        }

        public Criteria andFiledLocalNotBetween(String value1, String value2) {
            addCriterion("filed_local not between", value1, value2, "filedLocal");
            return (Criteria) this;
        }

        public Criteria andShowEnableIsNull() {
            addCriterion("show_enable is null");
            return (Criteria) this;
        }

        public Criteria andShowEnableIsNotNull() {
            addCriterion("show_enable is not null");
            return (Criteria) this;
        }

        public Criteria andShowEnableEqualTo(Integer value) {
            addCriterion("show_enable =", value, "showEnable");
            return (Criteria) this;
        }

        public Criteria andShowEnableNotEqualTo(Integer value) {
            addCriterion("show_enable <>", value, "showEnable");
            return (Criteria) this;
        }

        public Criteria andShowEnableGreaterThan(Integer value) {
            addCriterion("show_enable >", value, "showEnable");
            return (Criteria) this;
        }

        public Criteria andShowEnableGreaterThanOrEqualTo(Integer value) {
            addCriterion("show_enable >=", value, "showEnable");
            return (Criteria) this;
        }

        public Criteria andShowEnableLessThan(Integer value) {
            addCriterion("show_enable <", value, "showEnable");
            return (Criteria) this;
        }

        public Criteria andShowEnableLessThanOrEqualTo(Integer value) {
            addCriterion("show_enable <=", value, "showEnable");
            return (Criteria) this;
        }

        public Criteria andShowEnableIn(List<Integer> values) {
            addCriterion("show_enable in", values, "showEnable");
            return (Criteria) this;
        }

        public Criteria andShowEnableNotIn(List<Integer> values) {
            addCriterion("show_enable not in", values, "showEnable");
            return (Criteria) this;
        }

        public Criteria andShowEnableBetween(Integer value1, Integer value2) {
            addCriterion("show_enable between", value1, value2, "showEnable");
            return (Criteria) this;
        }

        public Criteria andShowEnableNotBetween(Integer value1, Integer value2) {
            addCriterion("show_enable not between", value1, value2, "showEnable");
            return (Criteria) this;
        }

        public Criteria andFiledDemoIsNull() {
            addCriterion("filed_demo is null");
            return (Criteria) this;
        }

        public Criteria andFiledDemoIsNotNull() {
            addCriterion("filed_demo is not null");
            return (Criteria) this;
        }

        public Criteria andFiledDemoEqualTo(String value) {
            addCriterion("filed_demo =", value, "filedDemo");
            return (Criteria) this;
        }

        public Criteria andFiledDemoNotEqualTo(String value) {
            addCriterion("filed_demo <>", value, "filedDemo");
            return (Criteria) this;
        }

        public Criteria andFiledDemoGreaterThan(String value) {
            addCriterion("filed_demo >", value, "filedDemo");
            return (Criteria) this;
        }

        public Criteria andFiledDemoGreaterThanOrEqualTo(String value) {
            addCriterion("filed_demo >=", value, "filedDemo");
            return (Criteria) this;
        }

        public Criteria andFiledDemoLessThan(String value) {
            addCriterion("filed_demo <", value, "filedDemo");
            return (Criteria) this;
        }

        public Criteria andFiledDemoLessThanOrEqualTo(String value) {
            addCriterion("filed_demo <=", value, "filedDemo");
            return (Criteria) this;
        }

        public Criteria andFiledDemoLike(String value) {
            addCriterion("filed_demo like", value, "filedDemo");
            return (Criteria) this;
        }

        public Criteria andFiledDemoNotLike(String value) {
            addCriterion("filed_demo not like", value, "filedDemo");
            return (Criteria) this;
        }

        public Criteria andFiledDemoIn(List<String> values) {
            addCriterion("filed_demo in", values, "filedDemo");
            return (Criteria) this;
        }

        public Criteria andFiledDemoNotIn(List<String> values) {
            addCriterion("filed_demo not in", values, "filedDemo");
            return (Criteria) this;
        }

        public Criteria andFiledDemoBetween(String value1, String value2) {
            addCriterion("filed_demo between", value1, value2, "filedDemo");
            return (Criteria) this;
        }

        public Criteria andFiledDemoNotBetween(String value1, String value2) {
            addCriterion("filed_demo not between", value1, value2, "filedDemo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_filed_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_filed_info
     *
     * @mbg.generated
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
