package com.certapp.dao.entity;

import java.util.ArrayList;
import java.util.List;

public class TbQueryPageExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    protected long start = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    protected long count = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public TbQueryPageExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public void setStart(long start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public long getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public void setCount(long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public long getCount() {
        return count;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdIsNull() {
            addCriterion("cert_config_id is null");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdIsNotNull() {
            addCriterion("cert_config_id is not null");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdEqualTo(Integer value) {
            addCriterion("cert_config_id =", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdNotEqualTo(Integer value) {
            addCriterion("cert_config_id <>", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdGreaterThan(Integer value) {
            addCriterion("cert_config_id >", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cert_config_id >=", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdLessThan(Integer value) {
            addCriterion("cert_config_id <", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdLessThanOrEqualTo(Integer value) {
            addCriterion("cert_config_id <=", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdIn(List<Integer> values) {
            addCriterion("cert_config_id in", values, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdNotIn(List<Integer> values) {
            addCriterion("cert_config_id not in", values, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdBetween(Integer value1, Integer value2) {
            addCriterion("cert_config_id between", value1, value2, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cert_config_id not between", value1, value2, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertOrgIsNull() {
            addCriterion("cert_org is null");
            return (Criteria) this;
        }

        public Criteria andCertOrgIsNotNull() {
            addCriterion("cert_org is not null");
            return (Criteria) this;
        }

        public Criteria andCertOrgEqualTo(String value) {
            addCriterion("cert_org =", value, "certOrg");
            return (Criteria) this;
        }

        public Criteria andCertOrgNotEqualTo(String value) {
            addCriterion("cert_org <>", value, "certOrg");
            return (Criteria) this;
        }

        public Criteria andCertOrgGreaterThan(String value) {
            addCriterion("cert_org >", value, "certOrg");
            return (Criteria) this;
        }

        public Criteria andCertOrgGreaterThanOrEqualTo(String value) {
            addCriterion("cert_org >=", value, "certOrg");
            return (Criteria) this;
        }

        public Criteria andCertOrgLessThan(String value) {
            addCriterion("cert_org <", value, "certOrg");
            return (Criteria) this;
        }

        public Criteria andCertOrgLessThanOrEqualTo(String value) {
            addCriterion("cert_org <=", value, "certOrg");
            return (Criteria) this;
        }

        public Criteria andCertOrgLike(String value) {
            addCriterion("cert_org like", value, "certOrg");
            return (Criteria) this;
        }

        public Criteria andCertOrgNotLike(String value) {
            addCriterion("cert_org not like", value, "certOrg");
            return (Criteria) this;
        }

        public Criteria andCertOrgIn(List<String> values) {
            addCriterion("cert_org in", values, "certOrg");
            return (Criteria) this;
        }

        public Criteria andCertOrgNotIn(List<String> values) {
            addCriterion("cert_org not in", values, "certOrg");
            return (Criteria) this;
        }

        public Criteria andCertOrgBetween(String value1, String value2) {
            addCriterion("cert_org between", value1, value2, "certOrg");
            return (Criteria) this;
        }

        public Criteria andCertOrgNotBetween(String value1, String value2) {
            addCriterion("cert_org not between", value1, value2, "certOrg");
            return (Criteria) this;
        }

        public Criteria andSearchHintIsNull() {
            addCriterion("search_hint is null");
            return (Criteria) this;
        }

        public Criteria andSearchHintIsNotNull() {
            addCriterion("search_hint is not null");
            return (Criteria) this;
        }

        public Criteria andSearchHintEqualTo(String value) {
            addCriterion("search_hint =", value, "searchHint");
            return (Criteria) this;
        }

        public Criteria andSearchHintNotEqualTo(String value) {
            addCriterion("search_hint <>", value, "searchHint");
            return (Criteria) this;
        }

        public Criteria andSearchHintGreaterThan(String value) {
            addCriterion("search_hint >", value, "searchHint");
            return (Criteria) this;
        }

        public Criteria andSearchHintGreaterThanOrEqualTo(String value) {
            addCriterion("search_hint >=", value, "searchHint");
            return (Criteria) this;
        }

        public Criteria andSearchHintLessThan(String value) {
            addCriterion("search_hint <", value, "searchHint");
            return (Criteria) this;
        }

        public Criteria andSearchHintLessThanOrEqualTo(String value) {
            addCriterion("search_hint <=", value, "searchHint");
            return (Criteria) this;
        }

        public Criteria andSearchHintLike(String value) {
            addCriterion("search_hint like", value, "searchHint");
            return (Criteria) this;
        }

        public Criteria andSearchHintNotLike(String value) {
            addCriterion("search_hint not like", value, "searchHint");
            return (Criteria) this;
        }

        public Criteria andSearchHintIn(List<String> values) {
            addCriterion("search_hint in", values, "searchHint");
            return (Criteria) this;
        }

        public Criteria andSearchHintNotIn(List<String> values) {
            addCriterion("search_hint not in", values, "searchHint");
            return (Criteria) this;
        }

        public Criteria andSearchHintBetween(String value1, String value2) {
            addCriterion("search_hint between", value1, value2, "searchHint");
            return (Criteria) this;
        }

        public Criteria andSearchHintNotBetween(String value1, String value2) {
            addCriterion("search_hint not between", value1, value2, "searchHint");
            return (Criteria) this;
        }

        public Criteria andExplainDocIsNull() {
            addCriterion("explain_doc is null");
            return (Criteria) this;
        }

        public Criteria andExplainDocIsNotNull() {
            addCriterion("explain_doc is not null");
            return (Criteria) this;
        }

        public Criteria andExplainDocEqualTo(String value) {
            addCriterion("explain_doc =", value, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocNotEqualTo(String value) {
            addCriterion("explain_doc <>", value, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocGreaterThan(String value) {
            addCriterion("explain_doc >", value, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocGreaterThanOrEqualTo(String value) {
            addCriterion("explain_doc >=", value, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocLessThan(String value) {
            addCriterion("explain_doc <", value, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocLessThanOrEqualTo(String value) {
            addCriterion("explain_doc <=", value, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocLike(String value) {
            addCriterion("explain_doc like", value, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocNotLike(String value) {
            addCriterion("explain_doc not like", value, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocIn(List<String> values) {
            addCriterion("explain_doc in", values, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocNotIn(List<String> values) {
            addCriterion("explain_doc not in", values, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocBetween(String value1, String value2) {
            addCriterion("explain_doc between", value1, value2, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocNotBetween(String value1, String value2) {
            addCriterion("explain_doc not between", value1, value2, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andFiledSerialIsNull() {
            addCriterion("filed_serial is null");
            return (Criteria) this;
        }

        public Criteria andFiledSerialIsNotNull() {
            addCriterion("filed_serial is not null");
            return (Criteria) this;
        }

        public Criteria andFiledSerialEqualTo(String value) {
            addCriterion("filed_serial =", value, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialNotEqualTo(String value) {
            addCriterion("filed_serial <>", value, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialGreaterThan(String value) {
            addCriterion("filed_serial >", value, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialGreaterThanOrEqualTo(String value) {
            addCriterion("filed_serial >=", value, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialLessThan(String value) {
            addCriterion("filed_serial <", value, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialLessThanOrEqualTo(String value) {
            addCriterion("filed_serial <=", value, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialLike(String value) {
            addCriterion("filed_serial like", value, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialNotLike(String value) {
            addCriterion("filed_serial not like", value, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialIn(List<String> values) {
            addCriterion("filed_serial in", values, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialNotIn(List<String> values) {
            addCriterion("filed_serial not in", values, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialBetween(String value1, String value2) {
            addCriterion("filed_serial between", value1, value2, "filedSerial");
            return (Criteria) this;
        }

        public Criteria andFiledSerialNotBetween(String value1, String value2) {
            addCriterion("filed_serial not between", value1, value2, "filedSerial");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_query_page
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
