package com.certapp.dao.entity;

import java.util.ArrayList;
import java.util.List;

public class TbQueryResultPageExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    protected long start = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    protected long count = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    public TbQueryResultPageExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    public void setStart(long start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    public long getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    public void setCount(long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    public long getCount() {
        return count;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdIsNull() {
            addCriterion("cert_config_id is null");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdIsNotNull() {
            addCriterion("cert_config_id is not null");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdEqualTo(Integer value) {
            addCriterion("cert_config_id =", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdNotEqualTo(Integer value) {
            addCriterion("cert_config_id <>", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdGreaterThan(Integer value) {
            addCriterion("cert_config_id >", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cert_config_id >=", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdLessThan(Integer value) {
            addCriterion("cert_config_id <", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdLessThanOrEqualTo(Integer value) {
            addCriterion("cert_config_id <=", value, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdIn(List<Integer> values) {
            addCriterion("cert_config_id in", values, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdNotIn(List<Integer> values) {
            addCriterion("cert_config_id not in", values, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdBetween(Integer value1, Integer value2) {
            addCriterion("cert_config_id between", value1, value2, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andCertConfigIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cert_config_id not between", value1, value2, "certConfigId");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andEnableFieldsIsNull() {
            addCriterion("enable_fields is null");
            return (Criteria) this;
        }

        public Criteria andEnableFieldsIsNotNull() {
            addCriterion("enable_fields is not null");
            return (Criteria) this;
        }

        public Criteria andEnableFieldsEqualTo(String value) {
            addCriterion("enable_fields =", value, "enableFields");
            return (Criteria) this;
        }

        public Criteria andEnableFieldsNotEqualTo(String value) {
            addCriterion("enable_fields <>", value, "enableFields");
            return (Criteria) this;
        }

        public Criteria andEnableFieldsGreaterThan(String value) {
            addCriterion("enable_fields >", value, "enableFields");
            return (Criteria) this;
        }

        public Criteria andEnableFieldsGreaterThanOrEqualTo(String value) {
            addCriterion("enable_fields >=", value, "enableFields");
            return (Criteria) this;
        }

        public Criteria andEnableFieldsLessThan(String value) {
            addCriterion("enable_fields <", value, "enableFields");
            return (Criteria) this;
        }

        public Criteria andEnableFieldsLessThanOrEqualTo(String value) {
            addCriterion("enable_fields <=", value, "enableFields");
            return (Criteria) this;
        }

        public Criteria andEnableFieldsLike(String value) {
            addCriterion("enable_fields like", value, "enableFields");
            return (Criteria) this;
        }

        public Criteria andEnableFieldsNotLike(String value) {
            addCriterion("enable_fields not like", value, "enableFields");
            return (Criteria) this;
        }

        public Criteria andEnableFieldsIn(List<String> values) {
            addCriterion("enable_fields in", values, "enableFields");
            return (Criteria) this;
        }

        public Criteria andEnableFieldsNotIn(List<String> values) {
            addCriterion("enable_fields not in", values, "enableFields");
            return (Criteria) this;
        }

        public Criteria andEnableFieldsBetween(String value1, String value2) {
            addCriterion("enable_fields between", value1, value2, "enableFields");
            return (Criteria) this;
        }

        public Criteria andEnableFieldsNotBetween(String value1, String value2) {
            addCriterion("enable_fields not between", value1, value2, "enableFields");
            return (Criteria) this;
        }

        public Criteria andExplainDocIsNull() {
            addCriterion("explain_doc is null");
            return (Criteria) this;
        }

        public Criteria andExplainDocIsNotNull() {
            addCriterion("explain_doc is not null");
            return (Criteria) this;
        }

        public Criteria andExplainDocEqualTo(String value) {
            addCriterion("explain_doc =", value, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocNotEqualTo(String value) {
            addCriterion("explain_doc <>", value, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocGreaterThan(String value) {
            addCriterion("explain_doc >", value, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocGreaterThanOrEqualTo(String value) {
            addCriterion("explain_doc >=", value, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocLessThan(String value) {
            addCriterion("explain_doc <", value, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocLessThanOrEqualTo(String value) {
            addCriterion("explain_doc <=", value, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocLike(String value) {
            addCriterion("explain_doc like", value, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocNotLike(String value) {
            addCriterion("explain_doc not like", value, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocIn(List<String> values) {
            addCriterion("explain_doc in", values, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocNotIn(List<String> values) {
            addCriterion("explain_doc not in", values, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocBetween(String value1, String value2) {
            addCriterion("explain_doc between", value1, value2, "explainDoc");
            return (Criteria) this;
        }

        public Criteria andExplainDocNotBetween(String value1, String value2) {
            addCriterion("explain_doc not between", value1, value2, "explainDoc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_query_result_page
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_query_result_page
     *
     * @mbg.generated
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
