package com.certapp.dao.entity;

import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@EqualsAndHashCode
public class TbQueryPage implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_query_page.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_query_page.cert_config_id
     *
     * @mbg.generated
     */
    private Integer certConfigId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_query_page.cert_org
     *
     * @mbg.generated
     */
    private String certOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_query_page.search_hint
     *
     * @mbg.generated
     */
    private String searchHint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_query_page.explain_doc
     *
     * @mbg.generated
     */
    private String explainDoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_query_page.filed_serial
     *
     * @mbg.generated
     */
    private String filedSerial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_query_page.banner
     *
     * @mbg.generated
     */
    private String banner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_query_page.bottom_log
     *
     * @mbg.generated
     */
    private String bottomLog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}
