package com.certapp.dao.mapper;

import com.certapp.dao.entity.TbCertConfig;
import com.certapp.dao.entity.TbCertConfigExample.Criteria;
import com.certapp.dao.entity.TbCertConfigExample.Criterion;
import com.certapp.dao.entity.TbCertConfigExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TbCertConfigSqlProvider {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public static final String ALL_COLUMN_FIELDS = "id,cert_name,filed_font,qr_code_url,qr_code_local,number_local,num_font,cert_desc,create_time,modify_time,cert_real,base_map,pic_preview";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public String countByExample(TbCertConfigExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("tb_cert_config");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public String deleteByExample(TbCertConfigExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("tb_cert_config");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public String insertSelective(TbCertConfig record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_cert_config");
        if (record.getCertName() != null) {
            sql.VALUES("cert_name", "#{certName,jdbcType=VARCHAR}");
        }
        if (record.getFiledFont() != null) {
            sql.VALUES("filed_font", "#{filedFont,jdbcType=VARCHAR}");
        }
        if (record.getQrCodeUrl() != null) {
            sql.VALUES("qr_code_url", "#{qrCodeUrl,jdbcType=VARCHAR}");
        }
        if (record.getQrCodeLocal() != null) {
            sql.VALUES("qr_code_local", "#{qrCodeLocal,jdbcType=VARCHAR}");
        }
        if (record.getNumberLocal() != null) {
            sql.VALUES("number_local", "#{numberLocal,jdbcType=VARCHAR}");
        }
        if (record.getNumFont() != null) {
            sql.VALUES("num_font", "#{numFont,jdbcType=VARCHAR}");
        }
        if (record.getCertDesc() != null) {
            sql.VALUES("cert_desc", "#{certDesc,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        if (record.getModifyTime() != null) {
            sql.VALUES("modify_time", "#{modifyTime,jdbcType=TIMESTAMP}");
        }
        if (record.getCertReal() != null) {
            sql.VALUES("cert_real", "#{certReal,jdbcType=INTEGER}");
        }
        if (record.getBaseMap() != null) {
            sql.VALUES("base_map", "#{baseMap,jdbcType=LONGVARCHAR}");
        }
        if (record.getPicPreview() != null) {
            sql.VALUES("pic_preview", "#{picPreview,jdbcType=LONGVARCHAR}");
        }
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public String selectByExampleWithBLOBs(TbCertConfigExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("cert_name");
        sql.SELECT("filed_font");
        sql.SELECT("qr_code_url");
        sql.SELECT("qr_code_local");
        sql.SELECT("number_local");
        sql.SELECT("num_font");
        sql.SELECT("cert_desc");
        sql.SELECT("create_time");
        sql.SELECT("modify_time");
        sql.SELECT("cert_real");
        sql.SELECT("base_map");
        sql.SELECT("pic_preview");
        sql.FROM("tb_cert_config");
        applyWhere(sql, example, false);
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        // add pagination for mysql with limit clause 
        StringBuilder sqlBuilder = new StringBuilder(sql.toString());
        if (example != null && (example.getStart() > -1 || example.getCount() > -1)) {
            sqlBuilder.append(" limit ");
            if (example.getStart() > -1 && example.getCount() > -1) {
                sqlBuilder.append(example.getStart()).append(",").append(example.getCount());
            } else if (example.getStart() > -1) {
                sqlBuilder.append(example.getStart());
            } else if (example.getCount() > -1) {
                sqlBuilder.append(example.getCount());
            }
        }
        return sqlBuilder.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public String selectByExample(TbCertConfigExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("cert_name");
        sql.SELECT("filed_font");
        sql.SELECT("qr_code_url");
        sql.SELECT("qr_code_local");
        sql.SELECT("number_local");
        sql.SELECT("num_font");
        sql.SELECT("cert_desc");
        sql.SELECT("create_time");
        sql.SELECT("modify_time");
        sql.SELECT("cert_real");
        sql.FROM("tb_cert_config");
        applyWhere(sql, example, false);
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        // add pagination for mysql with limit clause 
        StringBuilder sqlBuilder = new StringBuilder(sql.toString());
        if (example != null && (example.getStart() > -1 || example.getCount() > -1)) {
            sqlBuilder.append(" limit ");
            if (example.getStart() > -1 && example.getCount() > -1) {
                sqlBuilder.append(example.getStart()).append(",").append(example.getCount());
            } else if (example.getStart() > -1) {
                sqlBuilder.append(example.getStart());
            } else if (example.getCount() > -1) {
                sqlBuilder.append(example.getCount());
            }
        }
        return sqlBuilder.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TbCertConfig record = (TbCertConfig) parameter.get("record");
        TbCertConfigExample example = (TbCertConfigExample) parameter.get("example");
        SQL sql = new SQL();
        sql.UPDATE("tb_cert_config");
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        if (record.getCertName() != null) {
            sql.SET("cert_name = #{record.certName,jdbcType=VARCHAR}");
        }
        if (record.getFiledFont() != null) {
            sql.SET("filed_font = #{record.filedFont,jdbcType=VARCHAR}");
        }
        if (record.getQrCodeUrl() != null) {
            sql.SET("qr_code_url = #{record.qrCodeUrl,jdbcType=VARCHAR}");
        }
        if (record.getQrCodeLocal() != null) {
            sql.SET("qr_code_local = #{record.qrCodeLocal,jdbcType=VARCHAR}");
        }
        if (record.getNumberLocal() != null) {
            sql.SET("number_local = #{record.numberLocal,jdbcType=VARCHAR}");
        }
        if (record.getNumFont() != null) {
            sql.SET("num_font = #{record.numFont,jdbcType=VARCHAR}");
        }
        if (record.getCertDesc() != null) {
            sql.SET("cert_desc = #{record.certDesc,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        if (record.getModifyTime() != null) {
            sql.SET("modify_time = #{record.modifyTime,jdbcType=TIMESTAMP}");
        }
        if (record.getCertReal() != null) {
            sql.SET("cert_real = #{record.certReal,jdbcType=INTEGER}");
        }
        if (record.getBaseMap() != null) {
            sql.SET("base_map = #{record.baseMap,jdbcType=LONGVARCHAR}");
        }
        if (record.getPicPreview() != null) {
            sql.SET("pic_preview = #{record.picPreview,jdbcType=LONGVARCHAR}");
        }
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("tb_cert_config");
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("cert_name = #{record.certName,jdbcType=VARCHAR}");
        sql.SET("filed_font = #{record.filedFont,jdbcType=VARCHAR}");
        sql.SET("qr_code_url = #{record.qrCodeUrl,jdbcType=VARCHAR}");
        sql.SET("qr_code_local = #{record.qrCodeLocal,jdbcType=VARCHAR}");
        sql.SET("number_local = #{record.numberLocal,jdbcType=VARCHAR}");
        sql.SET("num_font = #{record.numFont,jdbcType=VARCHAR}");
        sql.SET("cert_desc = #{record.certDesc,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("modify_time = #{record.modifyTime,jdbcType=TIMESTAMP}");
        sql.SET("cert_real = #{record.certReal,jdbcType=INTEGER}");
        sql.SET("base_map = #{record.baseMap,jdbcType=LONGVARCHAR}");
        sql.SET("pic_preview = #{record.picPreview,jdbcType=LONGVARCHAR}");
        TbCertConfigExample example = (TbCertConfigExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("tb_cert_config");
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("cert_name = #{record.certName,jdbcType=VARCHAR}");
        sql.SET("filed_font = #{record.filedFont,jdbcType=VARCHAR}");
        sql.SET("qr_code_url = #{record.qrCodeUrl,jdbcType=VARCHAR}");
        sql.SET("qr_code_local = #{record.qrCodeLocal,jdbcType=VARCHAR}");
        sql.SET("number_local = #{record.numberLocal,jdbcType=VARCHAR}");
        sql.SET("num_font = #{record.numFont,jdbcType=VARCHAR}");
        sql.SET("cert_desc = #{record.certDesc,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("modify_time = #{record.modifyTime,jdbcType=TIMESTAMP}");
        sql.SET("cert_real = #{record.certReal,jdbcType=INTEGER}");
        TbCertConfigExample example = (TbCertConfigExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TbCertConfig record) {
        SQL sql = new SQL();
        sql.UPDATE("tb_cert_config");
        if (record.getCertName() != null) {
            sql.SET("cert_name = #{certName,jdbcType=VARCHAR}");
        }
        if (record.getFiledFont() != null) {
            sql.SET("filed_font = #{filedFont,jdbcType=VARCHAR}");
        }
        if (record.getQrCodeUrl() != null) {
            sql.SET("qr_code_url = #{qrCodeUrl,jdbcType=VARCHAR}");
        }
        if (record.getQrCodeLocal() != null) {
            sql.SET("qr_code_local = #{qrCodeLocal,jdbcType=VARCHAR}");
        }
        if (record.getNumberLocal() != null) {
            sql.SET("number_local = #{numberLocal,jdbcType=VARCHAR}");
        }
        if (record.getNumFont() != null) {
            sql.SET("num_font = #{numFont,jdbcType=VARCHAR}");
        }
        if (record.getCertDesc() != null) {
            sql.SET("cert_desc = #{certDesc,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        if (record.getModifyTime() != null) {
            sql.SET("modify_time = #{modifyTime,jdbcType=TIMESTAMP}");
        }
        if (record.getCertReal() != null) {
            sql.SET("cert_real = #{certReal,jdbcType=INTEGER}");
        }
        if (record.getBaseMap() != null) {
            sql.SET("base_map = #{baseMap,jdbcType=LONGVARCHAR}");
        }
        if (record.getPicPreview() != null) {
            sql.SET("pic_preview = #{picPreview,jdbcType=LONGVARCHAR}");
        }
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TbCertConfigExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_config
     *
     * @mbg.generated
     */
    public String getOneByExample(TbCertConfigExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("cert_name");
        sql.SELECT("filed_font");
        sql.SELECT("qr_code_url");
        sql.SELECT("qr_code_local");
        sql.SELECT("number_local");
        sql.SELECT("num_font");
        sql.SELECT("cert_desc");
        sql.SELECT("create_time");
        sql.SELECT("modify_time");
        sql.SELECT("cert_real");
        sql.SELECT("base_map");
        sql.SELECT("pic_preview");
        sql.FROM("tb_cert_config");
        applyWhere(sql, example, false);
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        StringBuilder sqlBuilder = new StringBuilder(sql.toString());
        sqlBuilder.append(" limit 1 ");
        return sqlBuilder.toString();
    }
}
