package com.certapp.dao.mapper;

import com.certapp.dao.entity.TbCertInfo;
import com.certapp.dao.entity.TbCertInfoExample.Criteria;
import com.certapp.dao.entity.TbCertInfoExample.Criterion;
import com.certapp.dao.entity.TbCertInfoExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TbCertInfoSqlProvider {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public static final String ALL_COLUMN_FIELDS = "id,cert_config_id,cert_id,filed_info,cert_hash,tx_hash,cert_url,cert_state,publish_state,cert_time,search_filed,cert_pic";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public String countByExample(TbCertInfoExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("tb_cert_info");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public String deleteByExample(TbCertInfoExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("tb_cert_info");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public String insertSelective(TbCertInfo record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_cert_info");
        if (record.getCertConfigId() != null) {
            sql.VALUES("cert_config_id", "#{certConfigId,jdbcType=INTEGER}");
        }
        if (record.getCertId() != null) {
            sql.VALUES("cert_id", "#{certId,jdbcType=VARCHAR}");
        }
        if (record.getFiledInfo() != null) {
            sql.VALUES("filed_info", "#{filedInfo,jdbcType=VARCHAR}");
        }
        if (record.getCertHash() != null) {
            sql.VALUES("cert_hash", "#{certHash,jdbcType=VARCHAR}");
        }
        if (record.getTxHash() != null) {
            sql.VALUES("tx_hash", "#{txHash,jdbcType=VARCHAR}");
        }
        if (record.getCertUrl() != null) {
            sql.VALUES("cert_url", "#{certUrl,jdbcType=VARCHAR}");
        }
        if (record.getCertState() != null) {
            sql.VALUES("cert_state", "#{certState,jdbcType=INTEGER}");
        }
        if (record.getPublishState() != null) {
            sql.VALUES("publish_state", "#{publishState,jdbcType=INTEGER}");
        }
        if (record.getCertTime() != null) {
            sql.VALUES("cert_time", "#{certTime,jdbcType=TIMESTAMP}");
        }
        if (record.getSearchFiled() != null) {
            sql.VALUES("search_filed", "#{searchFiled,jdbcType=VARCHAR}");
        }
        if (record.getCertPic() != null) {
            sql.VALUES("cert_pic", "#{certPic,jdbcType=LONGVARCHAR}");
        }
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public String selectByExampleWithBLOBs(TbCertInfoExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("cert_config_id");
        sql.SELECT("cert_id");
        sql.SELECT("filed_info");
        sql.SELECT("cert_hash");
        sql.SELECT("tx_hash");
        sql.SELECT("cert_url");
        sql.SELECT("cert_state");
        sql.SELECT("publish_state");
        sql.SELECT("cert_time");
        sql.SELECT("search_filed");
        sql.SELECT("cert_pic");
        sql.FROM("tb_cert_info");
        applyWhere(sql, example, false);
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        // add pagination for mysql with limit clause 
        StringBuilder sqlBuilder = new StringBuilder(sql.toString());
        if (example != null && (example.getStart() > -1 || example.getCount() > -1)) {
            sqlBuilder.append(" limit ");
            if (example.getStart() > -1 && example.getCount() > -1) {
                sqlBuilder.append(example.getStart()).append(",").append(example.getCount());
            } else if (example.getStart() > -1) {
                sqlBuilder.append(example.getStart());
            } else if (example.getCount() > -1) {
                sqlBuilder.append(example.getCount());
            }
        }
        return sqlBuilder.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public String selectByExample(TbCertInfoExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("cert_config_id");
        sql.SELECT("cert_id");
        sql.SELECT("filed_info");
        sql.SELECT("cert_hash");
        sql.SELECT("tx_hash");
        sql.SELECT("cert_url");
        sql.SELECT("cert_state");
        sql.SELECT("publish_state");
        sql.SELECT("cert_time");
        sql.SELECT("search_filed");
        sql.FROM("tb_cert_info");
        applyWhere(sql, example, false);
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        // add pagination for mysql with limit clause 
        StringBuilder sqlBuilder = new StringBuilder(sql.toString());
        if (example != null && (example.getStart() > -1 || example.getCount() > -1)) {
            sqlBuilder.append(" limit ");
            if (example.getStart() > -1 && example.getCount() > -1) {
                sqlBuilder.append(example.getStart()).append(",").append(example.getCount());
            } else if (example.getStart() > -1) {
                sqlBuilder.append(example.getStart());
            } else if (example.getCount() > -1) {
                sqlBuilder.append(example.getCount());
            }
        }
        return sqlBuilder.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TbCertInfo record = (TbCertInfo) parameter.get("record");
        TbCertInfoExample example = (TbCertInfoExample) parameter.get("example");
        SQL sql = new SQL();
        sql.UPDATE("tb_cert_info");
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        if (record.getCertConfigId() != null) {
            sql.SET("cert_config_id = #{record.certConfigId,jdbcType=INTEGER}");
        }
        if (record.getCertId() != null) {
            sql.SET("cert_id = #{record.certId,jdbcType=VARCHAR}");
        }
        if (record.getFiledInfo() != null) {
            sql.SET("filed_info = #{record.filedInfo,jdbcType=VARCHAR}");
        }
        if (record.getCertHash() != null) {
            sql.SET("cert_hash = #{record.certHash,jdbcType=VARCHAR}");
        }
        if (record.getTxHash() != null) {
            sql.SET("tx_hash = #{record.txHash,jdbcType=VARCHAR}");
        }
        if (record.getCertUrl() != null) {
            sql.SET("cert_url = #{record.certUrl,jdbcType=VARCHAR}");
        }
        if (record.getCertState() != null) {
            sql.SET("cert_state = #{record.certState,jdbcType=INTEGER}");
        }
        if (record.getPublishState() != null) {
            sql.SET("publish_state = #{record.publishState,jdbcType=INTEGER}");
        }
        if (record.getCertTime() != null) {
            sql.SET("cert_time = #{record.certTime,jdbcType=TIMESTAMP}");
        }
        if (record.getSearchFiled() != null) {
            sql.SET("search_filed = #{record.searchFiled,jdbcType=VARCHAR}");
        }
        if (record.getCertPic() != null) {
            sql.SET("cert_pic = #{record.certPic,jdbcType=LONGVARCHAR}");
        }
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("tb_cert_info");
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("cert_config_id = #{record.certConfigId,jdbcType=INTEGER}");
        sql.SET("cert_id = #{record.certId,jdbcType=VARCHAR}");
        sql.SET("filed_info = #{record.filedInfo,jdbcType=VARCHAR}");
        sql.SET("cert_hash = #{record.certHash,jdbcType=VARCHAR}");
        sql.SET("tx_hash = #{record.txHash,jdbcType=VARCHAR}");
        sql.SET("cert_url = #{record.certUrl,jdbcType=VARCHAR}");
        sql.SET("cert_state = #{record.certState,jdbcType=INTEGER}");
        sql.SET("publish_state = #{record.publishState,jdbcType=INTEGER}");
        sql.SET("cert_time = #{record.certTime,jdbcType=TIMESTAMP}");
        sql.SET("search_filed = #{record.searchFiled,jdbcType=VARCHAR}");
        sql.SET("cert_pic = #{record.certPic,jdbcType=LONGVARCHAR}");
        TbCertInfoExample example = (TbCertInfoExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("tb_cert_info");
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("cert_config_id = #{record.certConfigId,jdbcType=INTEGER}");
        sql.SET("cert_id = #{record.certId,jdbcType=VARCHAR}");
        sql.SET("filed_info = #{record.filedInfo,jdbcType=VARCHAR}");
        sql.SET("cert_hash = #{record.certHash,jdbcType=VARCHAR}");
        sql.SET("tx_hash = #{record.txHash,jdbcType=VARCHAR}");
        sql.SET("cert_url = #{record.certUrl,jdbcType=VARCHAR}");
        sql.SET("cert_state = #{record.certState,jdbcType=INTEGER}");
        sql.SET("publish_state = #{record.publishState,jdbcType=INTEGER}");
        sql.SET("cert_time = #{record.certTime,jdbcType=TIMESTAMP}");
        sql.SET("search_filed = #{record.searchFiled,jdbcType=VARCHAR}");
        TbCertInfoExample example = (TbCertInfoExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TbCertInfo record) {
        SQL sql = new SQL();
        sql.UPDATE("tb_cert_info");
        if (record.getCertConfigId() != null) {
            sql.SET("cert_config_id = #{certConfigId,jdbcType=INTEGER}");
        }
        if (record.getCertId() != null) {
            sql.SET("cert_id = #{certId,jdbcType=VARCHAR}");
        }
        if (record.getFiledInfo() != null) {
            sql.SET("filed_info = #{filedInfo,jdbcType=VARCHAR}");
        }
        if (record.getCertHash() != null) {
            sql.SET("cert_hash = #{certHash,jdbcType=VARCHAR}");
        }
        if (record.getTxHash() != null) {
            sql.SET("tx_hash = #{txHash,jdbcType=VARCHAR}");
        }
        if (record.getCertUrl() != null) {
            sql.SET("cert_url = #{certUrl,jdbcType=VARCHAR}");
        }
        if (record.getCertState() != null) {
            sql.SET("cert_state = #{certState,jdbcType=INTEGER}");
        }
        if (record.getPublishState() != null) {
            sql.SET("publish_state = #{publishState,jdbcType=INTEGER}");
        }
        if (record.getCertTime() != null) {
            sql.SET("cert_time = #{certTime,jdbcType=TIMESTAMP}");
        }
        if (record.getSearchFiled() != null) {
            sql.SET("search_filed = #{searchFiled,jdbcType=VARCHAR}");
        }
        if (record.getCertPic() != null) {
            sql.SET("cert_pic = #{certPic,jdbcType=LONGVARCHAR}");
        }
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TbCertInfoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cert_info
     *
     * @mbg.generated
     */
    public String getOneByExample(TbCertInfoExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("cert_config_id");
        sql.SELECT("cert_id");
        sql.SELECT("filed_info");
        sql.SELECT("cert_hash");
        sql.SELECT("tx_hash");
        sql.SELECT("cert_url");
        sql.SELECT("cert_state");
        sql.SELECT("publish_state");
        sql.SELECT("cert_time");
        sql.SELECT("search_filed");
        sql.SELECT("cert_pic");
        sql.FROM("tb_cert_info");
        applyWhere(sql, example, false);
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        StringBuilder sqlBuilder = new StringBuilder(sql.toString());
        sqlBuilder.append(" limit 1 ");
        return sqlBuilder.toString();
    }
}
