package com.certapp.dao.mapper;

import com.certapp.dao.entity.TbQueryPage;
import com.certapp.dao.entity.TbQueryPageExample.Criteria;
import com.certapp.dao.entity.TbQueryPageExample.Criterion;
import com.certapp.dao.entity.TbQueryPageExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TbQueryPageSqlProvider {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public static final String ALL_COLUMN_FIELDS = "id,cert_config_id,cert_org,search_hint,explain_doc,filed_serial,banner,bottom_log";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public String countByExample(TbQueryPageExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("tb_query_page");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public String deleteByExample(TbQueryPageExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("tb_query_page");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public String insertSelective(TbQueryPage record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_query_page");
        if (record.getCertConfigId() != null) {
            sql.VALUES("cert_config_id", "#{certConfigId,jdbcType=INTEGER}");
        }
        if (record.getCertOrg() != null) {
            sql.VALUES("cert_org", "#{certOrg,jdbcType=VARCHAR}");
        }
        if (record.getSearchHint() != null) {
            sql.VALUES("search_hint", "#{searchHint,jdbcType=VARCHAR}");
        }
        if (record.getExplainDoc() != null) {
            sql.VALUES("explain_doc", "#{explainDoc,jdbcType=VARCHAR}");
        }
        if (record.getFiledSerial() != null) {
            sql.VALUES("filed_serial", "#{filedSerial,jdbcType=VARCHAR}");
        }
        if (record.getBanner() != null) {
            sql.VALUES("banner", "#{banner,jdbcType=LONGVARCHAR}");
        }
        if (record.getBottomLog() != null) {
            sql.VALUES("bottom_log", "#{bottomLog,jdbcType=LONGVARCHAR}");
        }
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public String selectByExampleWithBLOBs(TbQueryPageExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("cert_config_id");
        sql.SELECT("cert_org");
        sql.SELECT("search_hint");
        sql.SELECT("explain_doc");
        sql.SELECT("filed_serial");
        sql.SELECT("banner");
        sql.SELECT("bottom_log");
        sql.FROM("tb_query_page");
        applyWhere(sql, example, false);
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        // add pagination for mysql with limit clause 
        StringBuilder sqlBuilder = new StringBuilder(sql.toString());
        if (example != null && (example.getStart() > -1 || example.getCount() > -1)) {
            sqlBuilder.append(" limit ");
            if (example.getStart() > -1 && example.getCount() > -1) {
                sqlBuilder.append(example.getStart()).append(",").append(example.getCount());
            } else if (example.getStart() > -1) {
                sqlBuilder.append(example.getStart());
            } else if (example.getCount() > -1) {
                sqlBuilder.append(example.getCount());
            }
        }
        return sqlBuilder.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public String selectByExample(TbQueryPageExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("cert_config_id");
        sql.SELECT("cert_org");
        sql.SELECT("search_hint");
        sql.SELECT("explain_doc");
        sql.SELECT("filed_serial");
        sql.FROM("tb_query_page");
        applyWhere(sql, example, false);
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        // add pagination for mysql with limit clause 
        StringBuilder sqlBuilder = new StringBuilder(sql.toString());
        if (example != null && (example.getStart() > -1 || example.getCount() > -1)) {
            sqlBuilder.append(" limit ");
            if (example.getStart() > -1 && example.getCount() > -1) {
                sqlBuilder.append(example.getStart()).append(",").append(example.getCount());
            } else if (example.getStart() > -1) {
                sqlBuilder.append(example.getStart());
            } else if (example.getCount() > -1) {
                sqlBuilder.append(example.getCount());
            }
        }
        return sqlBuilder.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TbQueryPage record = (TbQueryPage) parameter.get("record");
        TbQueryPageExample example = (TbQueryPageExample) parameter.get("example");
        SQL sql = new SQL();
        sql.UPDATE("tb_query_page");
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        if (record.getCertConfigId() != null) {
            sql.SET("cert_config_id = #{record.certConfigId,jdbcType=INTEGER}");
        }
        if (record.getCertOrg() != null) {
            sql.SET("cert_org = #{record.certOrg,jdbcType=VARCHAR}");
        }
        if (record.getSearchHint() != null) {
            sql.SET("search_hint = #{record.searchHint,jdbcType=VARCHAR}");
        }
        if (record.getExplainDoc() != null) {
            sql.SET("explain_doc = #{record.explainDoc,jdbcType=VARCHAR}");
        }
        if (record.getFiledSerial() != null) {
            sql.SET("filed_serial = #{record.filedSerial,jdbcType=VARCHAR}");
        }
        if (record.getBanner() != null) {
            sql.SET("banner = #{record.banner,jdbcType=LONGVARCHAR}");
        }
        if (record.getBottomLog() != null) {
            sql.SET("bottom_log = #{record.bottomLog,jdbcType=LONGVARCHAR}");
        }
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("tb_query_page");
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("cert_config_id = #{record.certConfigId,jdbcType=INTEGER}");
        sql.SET("cert_org = #{record.certOrg,jdbcType=VARCHAR}");
        sql.SET("search_hint = #{record.searchHint,jdbcType=VARCHAR}");
        sql.SET("explain_doc = #{record.explainDoc,jdbcType=VARCHAR}");
        sql.SET("filed_serial = #{record.filedSerial,jdbcType=VARCHAR}");
        sql.SET("banner = #{record.banner,jdbcType=LONGVARCHAR}");
        sql.SET("bottom_log = #{record.bottomLog,jdbcType=LONGVARCHAR}");
        TbQueryPageExample example = (TbQueryPageExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("tb_query_page");
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("cert_config_id = #{record.certConfigId,jdbcType=INTEGER}");
        sql.SET("cert_org = #{record.certOrg,jdbcType=VARCHAR}");
        sql.SET("search_hint = #{record.searchHint,jdbcType=VARCHAR}");
        sql.SET("explain_doc = #{record.explainDoc,jdbcType=VARCHAR}");
        sql.SET("filed_serial = #{record.filedSerial,jdbcType=VARCHAR}");
        TbQueryPageExample example = (TbQueryPageExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TbQueryPage record) {
        SQL sql = new SQL();
        sql.UPDATE("tb_query_page");
        if (record.getCertConfigId() != null) {
            sql.SET("cert_config_id = #{certConfigId,jdbcType=INTEGER}");
        }
        if (record.getCertOrg() != null) {
            sql.SET("cert_org = #{certOrg,jdbcType=VARCHAR}");
        }
        if (record.getSearchHint() != null) {
            sql.SET("search_hint = #{searchHint,jdbcType=VARCHAR}");
        }
        if (record.getExplainDoc() != null) {
            sql.SET("explain_doc = #{explainDoc,jdbcType=VARCHAR}");
        }
        if (record.getFiledSerial() != null) {
            sql.SET("filed_serial = #{filedSerial,jdbcType=VARCHAR}");
        }
        if (record.getBanner() != null) {
            sql.SET("banner = #{banner,jdbcType=LONGVARCHAR}");
        }
        if (record.getBottomLog() != null) {
            sql.SET("bottom_log = #{bottomLog,jdbcType=LONGVARCHAR}");
        }
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TbQueryPageExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_query_page
     *
     * @mbg.generated
     */
    public String getOneByExample(TbQueryPageExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("cert_config_id");
        sql.SELECT("cert_org");
        sql.SELECT("search_hint");
        sql.SELECT("explain_doc");
        sql.SELECT("filed_serial");
        sql.SELECT("banner");
        sql.SELECT("bottom_log");
        sql.FROM("tb_query_page");
        applyWhere(sql, example, false);
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        StringBuilder sqlBuilder = new StringBuilder(sql.toString());
        sqlBuilder.append(" limit 1 ");
        return sqlBuilder.toString();
    }
}
